### ISSUE TITLE
[BUG] Embedding file other than markdown

### ISSUE THREAD

**Issue by andynameistaken** [Mara-Li/mkdocs_embed_file_plugins#2]
**Describe the bug**

Plugin doesn't work

**To Reproduce**
- `mkdocs.yml`
```yml
#  Project information
site_name: 'Test'
site_description: 'Test'
site_author: 'Test'

# Plugins
plugins:
  - search
  - embed_file 
  
## Extensions
markdown_extensions:    
  - footnotes
  - pymdownx.highlight:
      linenums: true           
  - pymdownx.inlinehilite  
  - pymdownx.keys
  - pymdownx.snippets  
  - admonition
  - pymdownx.details  
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true

# ================================================
#         THEME                                                                                       #
# ================================================

theme:
  name: material
  font:
    # text: Sarala
    text: Montserrat
  features:
    - navigation.top
    - search.suggest    
    - search.highlight     
    - search.share        
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - header.autohide
    - content.code.annotate
  custom_dir: overrides

  language: 'en'
  # logo: 'images/logo.png'
  # favicon: 'images/logo.png'
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: deep purple
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: green
      # primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
 
# extra_css:
#   - 'stylesheets/extra.css'  ]
```

- *.md in docs/
 - Article.md:
 
```
# Introduction

![](CodeExample.java)
![[CodeExample.java]]
```

- CodeExample.java:
```java
public class CodeExample {
    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}
```

**Log** 
```
❯ mkdocs serve
INFO     -  Building documentation...
INFO     -  Cleaning site directory
INFO     -  Documentation built in 0.40 seconds
INFO     -  [00:22:14] Watching paths for changes: 'docs', 'mkdocs.yml'
INFO     -  [00:22:14] Serving on http://127.0.0.1:8000/
INFO     -  [00:22:14] Browser connected: http://127.0.0.1:8000/Article/
```

**Screenshots**

<img width="2048" alt="image" src="https://user-images.githubusercontent.com/15692002/193479188-01c7ea7f-9bef-4bf5-8ea0-53f781fd86df.png">

**Desktop :**
 - OS:
 ```
ProductName:	macOS
ProductVersion:	12.6
BuildVersion:	21G115
```
 - Browser: Safari 16.0, Firefox 105.0.1 (64-bit)

- `pip3 freeze`
```
❯ pip3 freeze
attrs==20.3.0
beautifulsoup4==4.11.1
bleach==5.0.1
CacheControl==0.12.11
cachy==0.3.0
certifi==2022.9.24
cffi==1.15.1
charset-normalizer==2.1.1
cleo==1.0.0a5
click==8.1.3
crashtest==0.3.1
defusedxml==0.7.1
distlib==0.3.6
dulwich==0.20.46
EditorConfig==0.12.3
entrypoints==0.4
fastjsonschema==2.16.2
filelock==3.8.0
ghp-import==2.1.0
html5lib==1.1
idna==3.4
jaraco.classes==3.2.3
Jinja2==3.1.2
jsbeautifier==1.14.6
jsonschema==4.16.0
jupyter-core==4.11.1
jupyter_client==7.3.5
jupyterlab-pygments==0.2.2
jupytext==1.14.1
keyring==23.9.3
lockfile==0.12.2
lxml==4.9.1
Markdown==3.3.7
markdown-it-py==2.1.0
MarkupSafe==2.1.1
mdit-py-plugins==0.3.1
mdurl==0.1.2
mdx-wikilink-plus==1.4.1
mergedeep==1.3.4
mistune==0.8.4
mkdocs==1.4.0
mkdocs-autolinks-plugin==0.6.0
mkdocs-callouts==1.7.0
mkdocs-custom-tags-attributes==0.2.1
mkdocs-embed-file-plugins==2.0.0
mkdocs-jupyter==0.22.0
mkdocs-literate-nav==0.5.0
mkdocs-markmap==2.3.0
mkdocs-material==8.5.3
mkdocs-material-extensions==1.0.3
mkdocs-mermaid2-plugin==0.6.0
mkdocs-roamlinks-plugin==0.2.0
more-itertools==8.14.0
msgpack==1.0.4
nbclient==0.6.8
nbconvert==6.5.4
nbformat==5.6.1
nest-asyncio==1.5.6
packaging==21.3
pandocfilters==1.5.0
pexpect==4.8.0
pkginfo==1.8.3
platformdirs==2.5.2
poetry==1.2.1
poetry-core==1.2.0
poetry-plugin-export==1.0.7
ptyprocess==0.7.0
pycparser==2.21
Pygments==2.13.0
pylev==1.4.0
pymdown-extensions==9.5
pyparsing==3.0.9
pyrsistent==0.18.1
python-dateutil==2.8.2
python-frontmatter==1.0.0
PyYAML==6.0
pyyaml_env_tag==0.1
pyzmq==24.0.1
requests==2.28.1
requests-toolbelt==0.9.1
shellingham==1.5.0
six==1.16.0
soupsieve==2.3.2.post1
tinycss2==1.1.1
toml==0.10.2
tomlkit==0.11.5
tornado==6.2
traitlets==5.4.0
urllib3==1.26.12
virtualenv==20.16.5
watchdog==2.1.9
webencodings==0.5.1
xattr==0.9.9
```
